<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Signature Application</title>

        <link href="http://fonts.googleapis.com/css?family=Roboto:100,400" rel="stylesheet" type="text/css">

        <style type="text/css">
            body {
                background-color: #232323;
                margin: 0;
                padding: 0;
                line-height: 1.65;
                font-family: 'Roboto';
                letter-spacing: 0.025em;
            }

            #Logo {
                display: block;
                margin: 40px 40px;
            }

            .infobox {
                font-weight: 100;
                background-color: #00A0D3;
                width: 60%;
                margin: 80px 40px;
                padding: 15px 30px;
                color: white;
            }

            .infobox h1, h2 {
                font-weight: 100;
                margin: 0 0 10px 0;
                padding: 0;
            }

            .infobox h1 {
                font-size: 48px;
                margin-left: -2px;
            }

            .infobox h2 {
                font-size: 25px;
            }

            .infobox p {
                margin: 0 0 10px 0;
                padding: 0;
                font-size: 16px;
            }

            .infobox ul, .infobox ol {
                margin: 0 0 10px 0;
            }

            .infobox b {
                font-weight: 400;
            }
        </style>
    </head>

    <body>
        <header>
            <img id="Logo" src="/modules/Signature/res/images/signature_logo.png" alt="Signature Logo" />
        </header>

        <main>
            <?= $this->content ?>
        </main>
    </body>
</html>
